/**
 * COMPREHENSIVE DOCUMENT LIBRARY
 * 
 * This library defines ALL document types that can be generated by the ADVERSIQ system.
 * It covers the full spectrum of global economic, governmental, institutional, and commercial needs.
 * 
 * The system is designed to serve:
 * - Governments (national, regional, municipal)
 * - Sovereign Wealth Funds
 * - Development Finance Institutions (DFIs)
 * - Multilateral Organizations (UN, World Bank, IMF, regional banks)
 * - Private Enterprises (Fortune 500 to SMEs)
 * - NGOs and Foundations
 * - Startups and Innovation Labs
 * - Financial Institutions (banks, insurers, funds)
 * - Academic and Research Institutions
 */

// ============================================================================
// DOCUMENT CATEGORY DEFINITIONS - THE 14 GLOBAL SCALE CATEGORIES
// ============================================================================
/**
 * The 14-Category Document Factory Structure
 * 
 * This structure ensures ADVERSIQ handles the entire lifecycle of global development projects:
 * 
 * ENTRY PHASE:    Strategy, Market, Government
 * DEAL PHASE:     Foundation, Financial, Partnership  
 * EXECUTION:      Project Management, Procurement, HR, Infrastructure
 * SAFETY PHASE:   Risk, Governance, Regulatory, ESG
 */

export type DocumentCategory = 
  // ===== THE 5 CORE CATEGORIES (Foundation) =====
  // 1. Foundation & Legal Documents
  | 'foundation-legal'
  // 2. Strategic Intelligence Documents
  | 'strategic-intelligence'
  // 3. Financial & Investment Documents
  | 'financial-investment'
  // 4. Risk & Due Diligence Documents
  | 'risk-due-diligence'
  // 5. Government & Policy Documents
  | 'government-policy'
  
  // ===== THE 9 ADDITIONAL CATEGORIES (Derived from System Architecture) =====
  // 6. Partnership & Consortium Agreements (from Step 4: Partners & Ecosystem)
  | 'partnership-consortium'
  // 7. Execution & Project Management (from Step 8 & Operator Persona)
  | 'execution-project-management'
  // 8. Governance & Board Reporting (from Step 9: Governance & Monitoring)
  | 'governance-board'
  // 9. Human Capital & Capability (from Step 7: Resources & Capability)
  | 'human-capital'
  // 10. Procurement & Supply Chain (from Operator Persona - Supply Chain)
  | 'procurement-supply-chain'
  // 11. ESG & Social Impact (from World Bank/Global Standards)
  | 'esg-social-impact'
  // 12. Regulatory & Compliance (from Regulator Persona)
  | 'regulatory-compliance'
  // 13. Communications & Investor Relations (from outreach letters)
  | 'communications-ir'
  // 14. Asset & Infrastructure Technical Specs (from Step 3: Market Context)
  | 'asset-infrastructure'
  
  // ===== LEGACY CATEGORIES (for backward compatibility) =====
  | 'foundation'
  | 'strategic'
  | 'legal'
  | 'financial'
  | 'risk'
  | 'government'
  | 'trade'
  | 'partnership'
  | 'intelligence'
  | 'operational'
  | 'communications'
  | 'technical'
  | 'esg'
  | 'research';

// ============================================================================
// 14-CATEGORY LIFECYCLE PHASE MAPPING
// ============================================================================

export type LifecyclePhase = 'entry' | 'deal' | 'execution' | 'safety';

export interface CategoryDefinition {
  id: DocumentCategory;
  name: string;
  shortName: string;
  description: string;
  purpose: string;
  derivedFrom: string;
  phase: LifecyclePhase;
  personaLink?: string;
  intakeStepLink?: string;
  documentExamples: string[];
  letterExamples: string[];
  color: string;
}

export const FOURTEEN_CATEGORY_DEFINITIONS: CategoryDefinition[] = [
  // ===== THE 5 CORE CATEGORIES =====
  {
    id: 'foundation-legal',
    name: '1. Foundation & Legal Documents',
    shortName: 'Foundation & Legal',
    description: 'Letters of Intent (LOI), Non-Disclosure Agreements (NDA), Term Sheets, Memorandums of Understanding (MOU)',
    purpose: 'Establishing the legal foundation for deals',
    derivedFrom: 'Core Foundation',
    phase: 'deal',
    documentExamples: ['Letter of Intent', 'NDA', 'Term Sheet', 'MOU', 'Expression of Interest', 'Pre-Qualification'],
    letterExamples: ['Partnership Introduction', 'Commitment Confirmation', 'Closing Confirmation'],
    color: 'blue',
  },
  {
    id: 'strategic-intelligence',
    name: '2. Strategic Intelligence Documents',
    shortName: 'Strategic Intelligence',
    description: 'Business Cases, Feasibility Studies, White Papers, Market Entry Strategies',
    purpose: 'Defining the "what" and "why" of the mandate',
    derivedFrom: 'Core Foundation',
    phase: 'entry',
    documentExamples: ['Business Case', 'Feasibility Study', 'White Paper', 'Market Entry Strategy', 'Strategic Plan', 'Executive Summary'],
    letterExamples: ['Ministerial Introduction', 'Investment Promotion Letter', 'Policy Advocacy Letter'],
    color: 'emerald',
  },
  {
    id: 'financial-investment',
    name: '3. Financial & Investment Documents',
    shortName: 'Financial & Investment',
    description: 'Full Financial Models, Private Placement Memorandums (PPM), Valuation Reports, Monte Carlo Simulations',
    purpose: 'Securing capital and proving economic viability (The Accountant Persona)',
    derivedFrom: 'Core Foundation',
    phase: 'deal',
    personaLink: 'The Accountant',
    documentExamples: ['Financial Model', 'PPM', 'Valuation Report', 'Monte Carlo Simulation', 'Investment Memo', 'Capital Raise Deck'],
    letterExamples: ['Investor Update', 'Capital Call Notice', 'Distribution Notice', 'Fundraising Teaser'],
    color: 'amber',
  },
  {
    id: 'risk-due-diligence',
    name: '4. Risk & Due Diligence Documents',
    shortName: 'Risk & Due Diligence',
    description: 'Comprehensive Due Diligence Reports, AML/KYC Checklists, Sanctions Screening Reports',
    purpose: 'Protecting against liability and fraud (The Skeptic Persona)',
    derivedFrom: 'Core Foundation',
    phase: 'safety',
    personaLink: 'The Skeptic',
    documentExamples: ['Due Diligence Report', 'AML/KYC Report', 'Sanctions Screening', 'Risk Register', 'Integrity DD', 'Political Risk Assessment'],
    letterExamples: ['Sanctions Clearance Request', 'AML Compliance Letter', 'Audit Response'],
    color: 'rose',
  },
  {
    id: 'government-policy',
    name: '5. Government & Policy Documents',
    shortName: 'Government & Policy',
    description: 'Policy Briefs, Cabinet Memos, Public-Private Partnership (PPP) Frameworks',
    purpose: 'Navigating political landscapes and securing public sector support',
    derivedFrom: 'Core Foundation',
    phase: 'entry',
    documentExamples: ['Policy Brief', 'Cabinet Memo', 'PPP Framework', 'Regulatory Impact Assessment', 'Grant Application', 'Subsidy Application'],
    letterExamples: ['Ministerial Introduction', 'Permit Application Cover', 'Government Contract Proposal', 'Trade Mission Request'],
    color: 'purple',
  },
  
  // ===== THE 9 ADDITIONAL CATEGORIES =====
  {
    id: 'partnership-consortium',
    name: '6. Partnership & Consortium Agreements',
    shortName: 'Partnership & Consortium',
    description: 'Joint Venture Agreements, Consortium Charters, Stakeholder Alignment Maps',
    purpose: 'Structuring multi-party collaborations and alliances',
    derivedFrom: 'Step 4: Partners & Ecosystem',
    phase: 'deal',
    intakeStepLink: 'Step 4',
    documentExamples: ['JV Agreement', 'Consortium Charter', 'Stakeholder Map', 'Alliance Framework', 'Teaming Agreement', 'Partnership Scorecard'],
    letterExamples: ['Partnership Introduction', 'JV Invitation', 'Strategic Alliance Proposal', 'Co-Investment Invitation'],
    color: 'blue',
  },
  {
    id: 'execution-project-management',
    name: '7. Execution & Project Management',
    shortName: 'Execution & PM',
    description: 'Implementation Roadmaps, 100-Day Plans, Gantt Charts, Critical Path Analyses',
    purpose: 'Operationalizing strategy into actionable plans',
    derivedFrom: 'Step 8: Execution Plan & The Operator Persona',
    phase: 'execution',
    personaLink: 'The Operator',
    intakeStepLink: 'Step 8',
    documentExamples: ['Implementation Roadmap', '100-Day Plan', 'Gantt Chart', 'Critical Path Analysis', 'Project Charter', 'Milestone Report'],
    letterExamples: ['Meeting Confirmation', 'Decision Confirmation', 'Instruction Acknowledgment'],
    color: 'amber',
  },
  {
    id: 'governance-board',
    name: '8. Governance & Board Reporting',
    shortName: 'Governance & Board',
    description: 'Board Charters, Monthly Steering Committee Reports, Decision Rights Matrices',
    purpose: 'Establishing oversight and accountability structures',
    derivedFrom: 'Step 9: Governance & Monitoring',
    phase: 'safety',
    intakeStepLink: 'Step 9',
    documentExamples: ['Board Charter', 'Steering Committee Report', 'Decision Rights Matrix', 'Governance Report', 'Annual Report', 'Board Presentation'],
    letterExamples: ['Annual Meeting Invitation', 'Proxy Solicitation', 'Decision Confirmation'],
    color: 'rose',
  },
  {
    id: 'human-capital',
    name: '9. Human Capital & Capability',
    shortName: 'Human Capital',
    description: 'Organizational Charts, Talent Gap Analyses, Key Personnel Bios',
    purpose: 'Building and assessing team capabilities',
    derivedFrom: 'Step 7: Resources & Capability',
    phase: 'execution',
    intakeStepLink: 'Step 7',
    documentExamples: ['Org Chart', 'Talent Gap Analysis', 'Key Personnel Bios', 'Capability Assessment', 'Training Materials', 'HR Due Diligence'],
    letterExamples: ['Offer Letter', 'Reference Letter', 'Promotion Letter', 'Secondment Agreement'],
    color: 'purple',
  },
  {
    id: 'procurement-supply-chain',
    name: '10. Procurement & Supply Chain',
    shortName: 'Procurement & Supply',
    description: 'Request for Proposals (RFP), Tender Documents, Vendor Assessment Scorecards',
    purpose: 'Managing sourcing and supplier relationships',
    derivedFrom: 'The Operator Persona (Supply Chain Robustness)',
    phase: 'execution',
    personaLink: 'The Operator',
    documentExamples: ['RFP', 'Tender Document', 'Vendor Scorecard', 'Procurement Strategy', 'Supply Chain Mapping', 'Vendor Assessment'],
    letterExamples: ['Vendor Onboarding', 'Purchase Order Cover', 'Quality Concern', 'Price Negotiation'],
    color: 'amber',
  },
  {
    id: 'esg-social-impact',
    name: '11. ESG & Social Impact',
    shortName: 'ESG & Social Impact',
    description: 'Environmental Impact Statements, Social License to Operate Audits, Community Benefit Plans',
    purpose: 'Meeting global sustainability and social responsibility standards',
    derivedFrom: 'Regional Development Context (World Bank/Global Standards)',
    phase: 'safety',
    documentExamples: ['Environmental Impact Statement', 'Social License Audit', 'Community Benefit Plan', 'ESG Report', 'Net Zero Roadmap', 'SDG Alignment'],
    letterExamples: ['Community Consultation', 'Humanitarian Cooperation', 'Cultural Exchange Proposal'],
    color: 'emerald',
  },
  {
    id: 'regulatory-compliance',
    name: '12. Regulatory & Compliance',
    shortName: 'Regulatory & Compliance',
    description: 'Permit Applications, Regulatory Clearance Timelines, Compliance Certificates',
    purpose: 'Navigating legal and regulatory requirements',
    derivedFrom: 'The Regulator Persona',
    phase: 'safety',
    personaLink: 'The Regulator',
    documentExamples: ['Permit Application', 'Regulatory Clearance Timeline', 'Compliance Certificate', 'Regulatory Filing', 'License Application', 'Regulatory Pathway'],
    letterExamples: ['License Renewal Request', 'Compliance Certification', 'Exemption Request', 'Appeal Letter'],
    color: 'rose',
  },
  {
    id: 'communications-ir',
    name: '13. Communications & Investor Relations',
    shortName: 'Communications & IR',
    description: 'Investor Updates, Press Releases, Community Consultation Decks',
    purpose: 'Managing stakeholder and public communications',
    derivedFrom: 'Outreach letters designed to break the ice',
    phase: 'entry',
    documentExamples: ['Investor Update', 'Press Release', 'Media Kit', 'Stakeholder Update', 'Crisis Communication', 'Case Study'],
    letterExamples: ['Investor Update', 'Press Release Cover', 'Media Inquiry Response', 'Crisis Statement'],
    color: 'blue',
  },
  {
    id: 'asset-infrastructure',
    name: '14. Asset & Infrastructure Technical Specs',
    shortName: 'Asset & Infrastructure',
    description: 'Site Selection Reports, Asset Utilization Plans, Technical Requirement Briefs',
    purpose: 'Defining physical and technical requirements',
    derivedFrom: 'Step 3: Market & Context - Infrastructure',
    phase: 'execution',
    intakeStepLink: 'Step 3',
    documentExamples: ['Site Selection Report', 'Asset Utilization Plan', 'Technical Requirements', 'Infrastructure Assessment', 'Grid Connection', 'Engineering Study'],
    letterExamples: ['Technical Inquiry', 'Site Visit Request', 'Capacity Inquiry'],
    color: 'amber',
  },
];

// ============================================================================
// LIFECYCLE PHASE DEFINITIONS
// ============================================================================

export const LIFECYCLE_PHASES: Record<LifecyclePhase, {
  name: string;
  description: string;
  categories: DocumentCategory[];
  color: string;
}> = {
  entry: {
    name: 'Entry Phase',
    description: 'Strategy, Market, Government',
    categories: ['strategic-intelligence', 'government-policy', 'communications-ir'],
    color: 'emerald',
  },
  deal: {
    name: 'Deal Phase',
    description: 'Foundation, Financial, Partnership',
    categories: ['foundation-legal', 'financial-investment', 'partnership-consortium'],
    color: 'blue',
  },
  execution: {
    name: 'Execution Phase',
    description: 'Project Management, Procurement, HR, Infrastructure',
    categories: ['execution-project-management', 'procurement-supply-chain', 'human-capital', 'asset-infrastructure'],
    color: 'amber',
  },
  safety: {
    name: 'Safety Phase',
    description: 'Risk, Governance, Regulatory, ESG',
    categories: ['risk-due-diligence', 'governance-board', 'regulatory-compliance', 'esg-social-impact'],
    color: 'rose',
  },
};

// Helper function to get category by ID
export const getCategoryDefinition = (categoryId: DocumentCategory): CategoryDefinition | undefined => {
  return FOURTEEN_CATEGORY_DEFINITIONS.find(cat => cat.id === categoryId);
};

// Helper function to get categories by lifecycle phase
export const getCategoriesByPhase = (phase: LifecyclePhase): CategoryDefinition[] => {
  return FOURTEEN_CATEGORY_DEFINITIONS.filter(cat => cat.phase === phase);
};

// Helper function to get categories linked to a persona
export const getCategoriesByPersona = (personaName: string): CategoryDefinition[] => {
  return FOURTEEN_CATEGORY_DEFINITIONS.filter(cat => cat.personaLink === personaName);
};

// Helper function to get categories linked to an intake step
export const getCategoriesByIntakeStep = (stepName: string): CategoryDefinition[] => {
  return FOURTEEN_CATEGORY_DEFINITIONS.filter(cat => cat.intakeStepLink === stepName);
};

// ============================================================================
// COMPREHENSIVE DOCUMENT TYPE UNION
// ============================================================================

export type ExtendedDocumentType =
  // === FOUNDATION DOCUMENTS (First Contact, Initial Outreach) ===
  | 'loi'                              // Letter of Intent
  | 'mou'                              // Memorandum of Understanding
  | 'nda'                              // Non-Disclosure Agreement
  | 'term-sheet'                       // Term Sheet
  | 'expression-of-interest'           // EOI
  | 'request-for-information'          // RFI
  | 'request-for-proposal'             // RFP
  | 'request-for-quotation'            // RFQ
  | 'invitation-to-tender'             // ITT
  | 'pre-qualification'                // Pre-Qualification Document
  
  // === STRATEGIC DOCUMENTS ===
  | 'executive-summary'                // 1-2 page overview
  | 'strategic-brief'                  // 3-5 page strategy outline
  | 'strategic-plan'                   // Full 10-20 page plan
  | 'business-case'                    // Investment justification
  | 'feasibility-study'                // Viability assessment
  | 'market-entry-strategy'            // Market expansion plan
  | 'growth-strategy'                  // Scaling roadmap
  | 'exit-strategy'                    // Divestiture/exit plan
  | 'turnaround-plan'                  // Business recovery
  | 'transformation-roadmap'           // Digital/organizational transformation
  | 'vision-document'                  // Long-term aspirational document
  | 'white-paper'                      // Thought leadership
  
  // === LEGAL & COMPLIANCE DOCUMENTS ===
  | 'joint-venture-agreement'          // JV structure
  | 'shareholders-agreement'           // Shareholder rights
  | 'partnership-agreement'            // Partnership terms
  | 'licensing-agreement'              // IP licensing
  | 'franchise-agreement'              // Franchise terms
  | 'distribution-agreement'           // Distribution rights
  | 'supply-agreement'                 // Supply chain contract
  | 'service-agreement'                // Service delivery
  | 'consulting-agreement'             // Advisory services
  | 'employment-agreement'             // Key personnel
  | 'compliance-certificate'           // Regulatory compliance
  | 'regulatory-filing'                // Government submission
  | 'sanctions-clearance'              // Sanctions verification
  | 'anti-corruption-policy'           // FCPA/UK Bribery Act
  | 'data-protection-policy'           // GDPR/privacy
  | 'dispute-resolution'               // Arbitration/mediation
  
  // === FINANCIAL & INVESTMENT DOCUMENTS ===
  | 'financial-model'                  // 5-year projections
  | 'investment-memo'                  // IC memo
  | 'investment-thesis'                // Investment rationale
  | 'capital-raise-deck'               // Fundraising materials
  | 'private-placement-memo'           // PPM
  | 'prospectus'                       // Public offering
  | 'bond-offering'                    // Debt issuance
  | 'project-finance-model'            // Infrastructure financing
  | 'valuation-report'                 // Company/asset valuation
  | 'fairness-opinion'                 // Transaction fairness
  | 'solvency-opinion'                 // Financial health
  | 'credit-analysis'                  // Credit assessment
  | 'cash-flow-analysis'               // Liquidity modeling
  | 'budget-proposal'                  // Budget justification
  | 'cost-benefit-analysis'            // CBA
  | 'roi-analysis'                     // Return analysis
  | 'npv-irr-analysis'                 // Discounted cash flow
  | 'sensitivity-analysis'             // Scenario modeling
  | 'monte-carlo-simulation'           // Probabilistic analysis
  
  // === RISK & DUE DILIGENCE ===
  | 'risk-assessment'                  // Comprehensive risk review
  | 'blind-spot-audit'                  // Blind spot audit
  | 'risk-register'                    // Risk inventory
  | 'risk-mitigation-plan'             // Risk controls
  | 'due-diligence-request'            // Information request
  | 'due-diligence-report'             // DD findings
  | 'legal-due-diligence'              // Legal DD
  | 'financial-due-diligence'          // Financial DD
  | 'commercial-due-diligence'         // Commercial DD
  | 'technical-due-diligence'          // Technical DD
  | 'environmental-due-diligence'      // Environmental DD
  | 'tax-due-diligence'                // Tax DD
  | 'hr-due-diligence'                 // People DD
  | 'it-due-diligence'                 // Technology DD
  | 'background-check'                 // Entity verification
  | 'integrity-due-diligence'          // Corruption/sanctions
  | 'sanctions-screening'              // OFAC/EU/UN screening
  | 'aml-kyc-report'                   // Anti-money laundering
  | 'political-risk-assessment'        // Country/political risk
  | 'country-risk-report'              // Sovereign risk
  | 'currency-risk-analysis'           // FX exposure
  | 'insurance-gap-analysis'           // Coverage assessment
  
  // === GOVERNMENT & POLICY DOCUMENTS ===
  | 'policy-brief'                     // Policy recommendation
  | 'position-paper'                   // Advocacy document
  | 'regulatory-impact-assessment'     // RIA
  | 'legislative-proposal'             // Draft legislation
  | 'cabinet-memo'                     // Government decision memo
  | 'ministerial-briefing'             // Minister brief
  | 'budget-submission'                // Government budget
  | 'public-consultation'              // Citizen engagement
  | 'public-private-partnership'       // PPP proposal
  | 'concession-agreement'             // Infrastructure concession
  | 'sovereign-guarantee'              // Government guarantee
  | 'bilateral-investment-treaty'      // BIT template
  | 'free-trade-agreement'             // FTA analysis
  | 'economic-impact-assessment'       // EIA
  | 'social-impact-assessment'         // SIA
  | 'national-development-plan'        // NDP contribution
  | 'sector-development-strategy'      // Industry policy
  | 'special-economic-zone'            // SEZ proposal
  | 'investment-promotion'             // FDI attraction
  | 'grant-application'                // Funding request
  | 'subsidy-application'              // Incentive request
  
  // === TRADE & COMMERCE ===
  | 'export-plan'                      // Export strategy
  | 'import-analysis'                  // Import sourcing
  | 'trade-finance-proposal'           // Trade financing
  | 'letter-of-credit'                 // LC documentation
  | 'bill-of-lading'                   // Shipping documentation
  | 'customs-declaration'              // Import/export filing
  | 'origin-certificate'               // Certificate of origin
  | 'trade-compliance'                 // Export control
  | 'market-access-analysis'           // Trade barrier analysis
  | 'tariff-analysis'                  // Duty calculation
  | 'supply-chain-mapping'             // Value chain analysis
  | 'procurement-strategy'             // Sourcing plan
  | 'vendor-assessment'                // Supplier evaluation
  
  // === PARTNERSHIP & ALLIANCE ===
  | 'proposal'                         // Partnership proposal
  | 'partnership-assessment'           // Partner evaluation
  | 'partner-comparison'               // Partner comparison matrix
  | 'alliance-framework'               // Strategic alliance
  | 'consortium-agreement'             // Multi-party partnership
  | 'teaming-agreement'                // Joint bid
  | 'co-development-agreement'         // Joint development
  | 'technology-transfer'              // Tech transfer terms
  | 'capacity-building'                // Training program
  | 'local-content-plan'               // Local sourcing
  | 'stakeholder-mapping'              // Stakeholder analysis
  | 'stakeholder-engagement'           // Engagement strategy
  | 'relationship-plan'                // Account management
  | 'partnership-scorecard'            // Partnership health
  
  // === MARKET INTELLIGENCE ===
  | 'dossier'                          // Full market dossier
  | 'market-analysis'                  // Market overview
  | 'industry-analysis'                // Sector deep-dive
  | 'competitive-analysis'             // Competitor landscape
  | 'competitive-intelligence'         // CI report
  | 'swot-analysis'                    // SWOT
  | 'pestle-analysis'                  // PESTLE
  | 'porter-five-forces'               // Industry structure
  | 'value-chain-analysis'             // Value chain
  | 'customer-analysis'                // Buyer behavior
  | 'market-sizing'                    // TAM/SAM/SOM
  | 'trend-analysis'                   // Market trends
  | 'technology-assessment'            // Tech landscape
  | 'innovation-scan'                  // Emerging tech
  | 'business-intelligence-report'     // BI report
  | 'location-analysis'                // Site selection
  | 'labor-market-analysis'            // Workforce assessment
  | 'wage-survey'                      // Compensation study
  | 'real-estate-analysis'             // Property market
  | 'infrastructure-assessment'        // Infra evaluation
  | 'cultural-brief'                   // Cultural intelligence
  | 'entry-advisory'                   // Market entry guide
  
  // === OPERATIONAL DOCUMENTS ===
  | 'operational-plan'                 // Operations roadmap
  | 'implementation-plan'              // Execution timeline
  | 'project-charter'                  // Project authorization
  | 'project-plan'                     // Project management
  | 'milestone-report'                 // Progress tracking
  | 'status-report'                    // Periodic update
  | 'lessons-learned'                  // Post-mortem
  | 'change-management'                // Change program
  | 'integration-plan'                 // M&A integration
  | 'post-merger-integration'          // PMI playbook
  | 'transition-plan'                  // Handover document
  | 'continuity-plan'                  // Business continuity
  | 'disaster-recovery'                // DR plan
  | 'quality-management'               // QMS documentation
  | 'process-documentation'            // SOP
  | 'training-materials'               // Training program
  | 'performance-metrics'              // KPI framework
  | 'dashboard-design'                 // Reporting design
  
  // === COMMUNICATIONS & PR ===
  | 'press-release'                    // Media announcement
  | 'media-kit'                        // Press materials
  | 'investor-presentation'            // Investor deck
  | 'board-presentation'               // Board deck
  | 'annual-report'                    // Yearly report
  | 'quarterly-report'                 // Quarterly update
  | 'shareholder-letter'               // Investor letter
  | 'stakeholder-update'               // Stakeholder comms
  | 'crisis-communication'             // Crisis PR
  | 'internal-memo'                    // Employee comms
  | 'newsletter'                       // Periodic update
  | 'case-study'                       // Success story
  | 'testimonial-collection'           // Client references
  | 'faqs'                             // Q&A document
  | 'talking-points'                   // Speaker brief
  | 'speech-draft'                     // Executive speech
  | 'op-ed'                            // Opinion piece
  
  // === ESG & SUSTAINABILITY ===
  | 'esg-report'                       // ESG disclosure
  | 'sustainability-report'            // Sustainability disclosure
  | 'carbon-footprint'                 // GHG assessment
  | 'net-zero-roadmap'                 // Decarbonization plan
  | 'environmental-impact'             // EIA
  | 'social-impact'                    // SIA
  | 'community-engagement'             // Community plan
  | 'human-rights-assessment'          // HRDD
  | 'labor-standards'                  // Worker conditions
  | 'supply-chain-audit'               // Ethical sourcing
  | 'diversity-inclusion'              // D&I report
  | 'governance-report'                // Corporate governance
  | 'ethics-policy'                    // Code of conduct
  | 'whistleblower-policy'             // Reporting mechanism
  | 'anti-bribery-program'             // ABC program
  | 'green-bond-framework'             // Green financing
  | 'social-bond-framework'            // Social financing
  | 'impact-measurement'               // Impact metrics
  | 'sdg-alignment'                    // UN SDG mapping
  
  // === TECHNICAL & SECTOR-SPECIFIC ===
  | 'technical-specification'          // Technical requirements
  | 'technology-roadmap'               // Tech evolution plan
  | 'patent-analysis'                  // IP landscape
  | 'regulatory-pathway'               // Approval strategy
  | 'clinical-trial-design'            // Healthcare trials
  | 'safety-assessment'                // Product safety
  | 'engineering-study'                // Technical study
  | 'feasibility-engineering'          // Engineering feasibility
  | 'resource-assessment'              // Natural resources
  | 'reserve-report'                   // Mining/oil reserves
  | 'grid-connection'                  // Energy infrastructure
  | 'power-purchase-agreement'         // PPA
  | 'offtake-agreement'                // Commodity offtake
  | 'construction-contract'            // EPC/construction
  | 'maintenance-agreement'            // O&M
  | 'telecom-license'                  // Spectrum/license
  | 'fintech-compliance'               // Financial tech rules
  
  // === RESEARCH & ACADEMIC ===
  | 'research-proposal'                // Academic research
  | 'literature-review'                // Academic review
  | 'methodology'                      // Research method
  | 'data-analysis'                    // Statistical analysis
  | 'findings-report'                  // Research findings
  | 'policy-recommendation'            // Evidence-based policy
  | 'economic-model'                   // Economic modeling
  | 'scenario-analysis'                // Future scenarios
  | 'forecasting-report'               // Projections
  | 'benchmarking-study'               // Comparative analysis
  | 'best-practices'                   // Industry standards
  | 'lessons-from-history'             // Historical analysis
  | 'precedent-analysis'               // Case comparison;

// ============================================================================
// PAGE LENGTH OPTIONS
// ============================================================================

export type PageLength = 1 | 2 | 3 | 4 | 5 | 10 | 15 | 20 | 25 | 30 | 50 | 75 | 100;

export const PAGE_LENGTH_OPTIONS: PageLength[] = [1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 50, 75, 100];

export interface PageLengthPreset {
  value: PageLength;
  label: string;
  description: string;
  useCase: string;
}

export const PAGE_LENGTH_PRESETS: PageLengthPreset[] = [
  { value: 1, label: '1 Page', description: 'Quick summary', useCase: 'Email attachment, quick brief' },
  { value: 2, label: '2 Pages', description: 'Executive brief', useCase: 'Board summary, investor teaser' },
  { value: 3, label: '3 Pages', description: 'Concise report', useCase: 'Decision memo, proposal summary' },
  { value: 5, label: '5 Pages', description: 'Standard brief', useCase: 'Project brief, strategy outline' },
  { value: 10, label: '10 Pages', description: 'Full report', useCase: 'Business case, market analysis' },
  { value: 15, label: '15 Pages', description: 'Detailed report', useCase: 'Due diligence, feasibility study' },
  { value: 20, label: '20 Pages', description: 'Comprehensive', useCase: 'Full dossier, strategic plan' },
  { value: 25, label: '25 Pages', description: 'Extended analysis', useCase: 'Sector study, policy paper' },
  { value: 30, label: '30 Pages', description: 'Full study', useCase: 'Industry report, research paper' },
  { value: 50, label: '50 Pages', description: 'Major report', useCase: 'Annual report, master plan' },
  { value: 75, label: '75 Pages', description: 'Comprehensive study', useCase: 'National strategy, sector master plan' },
  { value: 100, label: '100 Pages', description: 'Full documentation', useCase: 'Complete project documentation' },
];

// ============================================================================
// DOCUMENT TEMPLATE INTERFACE
// ============================================================================

export interface DocumentTemplate {
  id: ExtendedDocumentType;
  title: string;
  description: string;
  category: DocumentCategory;
  defaultPageLength: PageLength;
  minPageLength: PageLength;
  maxPageLength: PageLength;
  timeToGenerate: string;
  requiredInputs: string[];
  optionalInputs: string[];
  outputFormats: ('pdf' | 'docx' | 'html' | 'md' | 'txt')[];
  useCases: string[];
  targetAudience: string[];
  sections: string[];
  aiCapabilities: string[];
}

// ============================================================================
// DOCUMENT TEMPLATES LIBRARY
// ============================================================================

export const EXTENDED_DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  // === FOUNDATION DOCUMENTS ===
  {
    id: 'loi',
    title: 'Letter of Intent',
    description: 'Non-binding expression of partnership interest with key terms and conditions',
    category: 'foundation',
    defaultPageLength: 2,
    minPageLength: 1,
    maxPageLength: 5,
    timeToGenerate: '< 2 min',
    requiredInputs: ['entityName', 'counterparty', 'jurisdiction'],
    optionalInputs: ['dealValue', 'timeline', 'keyTerms'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Initial outreach', 'Preliminary agreement', 'Negotiation start'],
    targetAudience: ['Legal', 'Executive', 'Partner'],
    sections: ['Introduction', 'Intent', 'Key Terms', 'Conditions', 'Signatures'],
    aiCapabilities: ['Precedent matching', 'Legal language optimization', 'Risk flagging'],
  },
  {
    id: 'mou',
    title: 'Memorandum of Understanding',
    description: 'Framework agreement establishing principles before detailed negotiation',
    category: 'foundation',
    defaultPageLength: 5,
    minPageLength: 2,
    maxPageLength: 15,
    timeToGenerate: '< 3 min',
    requiredInputs: ['entityName', 'counterparty', 'scope'],
    optionalInputs: ['governance', 'timeline', 'confidentiality'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Government partnerships', 'Multi-party agreements', 'Research collaborations'],
    targetAudience: ['Legal', 'Government', 'Executive'],
    sections: ['Preamble', 'Definitions', 'Scope', 'Responsibilities', 'Governance', 'Term'],
    aiCapabilities: ['Clause suggestion', 'Precedent analysis', 'Stakeholder mapping'],
  },
  {
    id: 'executive-summary',
    title: 'Executive Summary',
    description: 'High-level strategic overview with key findings and recommendations',
    category: 'strategic',
    defaultPageLength: 2,
    minPageLength: 1,
    maxPageLength: 5,
    timeToGenerate: '< 2 min',
    requiredInputs: ['entityName', 'strategicIntent'],
    optionalInputs: ['market', 'financials', 'risks'],
    outputFormats: ['pdf', 'docx', 'html'],
    useCases: ['Board presentation', 'Investor pitch', 'Decision memo'],
    targetAudience: ['C-Suite', 'Board', 'Investors'],
    sections: ['Overview', 'Opportunity', 'Strategy', 'Financials', 'Risks', 'Recommendation'],
    aiCapabilities: ['Auto-summarization', 'Key insight extraction', 'Visual generation'],
  },
  {
    id: 'dossier',
    title: 'Comprehensive Market Dossier',
    description: 'Complete intelligence package covering market, partners, risks, and strategy',
    category: 'intelligence',
    defaultPageLength: 20,
    minPageLength: 10,
    maxPageLength: 100,
    timeToGenerate: '< 10 min',
    requiredInputs: ['entityName', 'targetMarket', 'strategicIntent'],
    optionalInputs: ['competitors', 'partners', 'financials', 'regulations'],
    outputFormats: ['pdf', 'docx', 'html'],
    useCases: ['Market entry', 'Investment decision', 'Board briefing'],
    targetAudience: ['Executive', 'Board', 'Investment Committee'],
    sections: ['Executive Summary', 'Market Analysis', 'Competitive Landscape', 'Partner Assessment', 'Risk Analysis', 'Financial Projections', 'Implementation Plan', 'Appendices'],
    aiCapabilities: ['Multi-source synthesis', 'Precedent matching', 'Risk scoring', 'RROI calculation', 'SEAM analysis'],
  },
  {
    id: 'risk-assessment',
    title: 'Risk Assessment Report',
    description: 'Comprehensive identification, analysis, and mitigation of all risk categories',
    category: 'risk',
    defaultPageLength: 15,
    minPageLength: 5,
    maxPageLength: 50,
    timeToGenerate: '< 5 min',
    requiredInputs: ['entityName', 'projectScope', 'jurisdiction'],
    optionalInputs: ['financials', 'partners', 'timeline'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Investment approval', 'Board decision', 'Insurance'],
    targetAudience: ['Risk Committee', 'Board', 'Insurers'],
    sections: ['Executive Summary', 'Risk Register', 'Political Risk', 'Market Risk', 'Operational Risk', 'Financial Risk', 'Legal Risk', 'Mitigation Plan', 'Monitoring Framework'],
    aiCapabilities: ['Historical risk analysis', 'Monte Carlo simulation', 'Precedent matching', 'Ethics check'],
  },
  {
    id: 'blind-spot-audit',
    title: 'Blind Spot Audit',
    description: 'Unbiased audit that surfaces hidden failure modes, sequencing gaps, and verification risks',
    category: 'risk',
    defaultPageLength: 5,
    minPageLength: 3,
    maxPageLength: 20,
    timeToGenerate: '< 4 min',
    requiredInputs: ['entityName', 'jurisdiction', 'counterparty'],
    optionalInputs: ['financials', 'timeline', 'governance', 'evidence'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Pre-signing review', 'Deal risk hardening', 'Board diligence'],
    targetAudience: ['Executive', 'Board', 'Risk Committee'],
    sections: ['Purpose', 'Formula Scores', 'Blind Spot Findings', 'Timing & Sequencing Risks', 'Verification Gaps', 'Dependency Risks', 'Governance Weaknesses', 'Hardening Actions'],
    aiCapabilities: ['Bias detection', 'Dependency analysis', 'Formula scoring', 'Evidence validation'],
  },
  {
    id: 'financial-model',
    title: 'Financial Model & Projections',
    description: '5-year financial projections with scenarios, sensitivities, and valuation',
    category: 'financial',
    defaultPageLength: 10,
    minPageLength: 3,
    maxPageLength: 30,
    timeToGenerate: '< 5 min',
    requiredInputs: ['entityName', 'investmentAmount', 'revenueAssumptions'],
    optionalInputs: ['costStructure', 'capitalStructure', 'exitAssumptions'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Investment decision', 'Fundraising', 'Valuation'],
    targetAudience: ['CFO', 'Investors', 'Board'],
    sections: ['Assumptions', 'Revenue Model', 'Cost Structure', 'Cash Flow', 'P&L', 'Balance Sheet', 'Valuation', 'Sensitivities', 'Scenarios'],
    aiCapabilities: ['SPI calculation', 'IVAS analysis', 'SCF optimization', 'Monte Carlo simulation'],
  },
  {
    id: 'investment-memo',
    title: 'Investment Memorandum',
    description: 'Complete investment justification for committee approval',
    category: 'financial',
    defaultPageLength: 15,
    minPageLength: 5,
    maxPageLength: 50,
    timeToGenerate: '< 8 min',
    requiredInputs: ['entityName', 'investmentAmount', 'targetCompany'],
    optionalInputs: ['valuation', 'dueDiligence', 'terms'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['IC approval', 'Board authorization', 'LP reporting'],
    targetAudience: ['Investment Committee', 'Board', 'LPs'],
    sections: ['Executive Summary', 'Investment Thesis', 'Market Opportunity', 'Company Overview', 'Financials', 'Valuation', 'Risks', 'Terms', 'Recommendation'],
    aiCapabilities: ['Precedent analysis', 'Valuation modeling', 'Risk scoring', 'Comparable deals'],
  },
  {
    id: 'due-diligence-report',
    title: 'Due Diligence Report',
    description: 'Comprehensive findings from legal, financial, and commercial due diligence',
    category: 'risk',
    defaultPageLength: 30,
    minPageLength: 10,
    maxPageLength: 100,
    timeToGenerate: '< 15 min',
    requiredInputs: ['entityName', 'targetCompany', 'ddScope'],
    optionalInputs: ['financials', 'legal', 'commercial', 'technical'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['M&A', 'Investment', 'Partnership'],
    targetAudience: ['Board', 'Legal', 'Investment Team'],
    sections: ['Executive Summary', 'Legal DD', 'Financial DD', 'Commercial DD', 'Technical DD', 'HR DD', 'Tax DD', 'Environmental', 'Red Flags', 'Recommendations'],
    aiCapabilities: ['Document analysis', 'Risk flagging', 'Compliance check', 'Entity verification'],
  },
  {
    id: 'policy-brief',
    title: 'Policy Brief',
    description: 'Evidence-based policy recommendation for government decision-makers',
    category: 'government',
    defaultPageLength: 5,
    minPageLength: 2,
    maxPageLength: 15,
    timeToGenerate: '< 3 min',
    requiredInputs: ['policyTopic', 'jurisdiction', 'recommendation'],
    optionalInputs: ['evidence', 'stakeholders', 'implementation'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Policy advocacy', 'Government briefing', 'Regulatory input'],
    targetAudience: ['Ministers', 'Policy Makers', 'Legislators'],
    sections: ['Issue', 'Background', 'Evidence', 'Options', 'Recommendation', 'Implementation'],
    aiCapabilities: ['Historical precedent', 'Economic impact modeling', 'Stakeholder analysis'],
  },
  {
    id: 'esg-report',
    title: 'ESG Assessment Report',
    description: 'Environmental, Social, and Governance impact assessment and disclosure',
    category: 'esg',
    defaultPageLength: 20,
    minPageLength: 5,
    maxPageLength: 75,
    timeToGenerate: '< 10 min',
    requiredInputs: ['entityName', 'operations', 'geography'],
    optionalInputs: ['emissions', 'workforce', 'governance'],
    outputFormats: ['pdf', 'docx', 'html'],
    useCases: ['Investor disclosure', 'Regulatory compliance', 'Stakeholder reporting'],
    targetAudience: ['Investors', 'Regulators', 'Stakeholders'],
    sections: ['Executive Summary', 'Environmental', 'Social', 'Governance', 'Metrics', 'SDG Alignment', 'Improvement Plan', 'Assurance'],
    aiCapabilities: ['SDG mapping', 'Carbon calculation', 'Benchmark comparison', 'TCFD alignment'],
  },
  {
    id: 'precedent-analysis',
    title: 'Historical Precedent Analysis',
    description: 'Deep analysis of historical cases and patterns relevant to current situation',
    category: 'research',
    defaultPageLength: 15,
    minPageLength: 5,
    maxPageLength: 50,
    timeToGenerate: '< 8 min',
    requiredInputs: ['currentSituation', 'industry', 'geography'],
    optionalInputs: ['timeframe', 'specificPrecedents'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Strategy development', 'Risk assessment', 'Decision support'],
    targetAudience: ['Strategy', 'Board', 'Advisors'],
    sections: ['Current Context', 'Methodology', 'Historical Cases', 'Pattern Analysis', 'Lessons Learned', 'Application', 'Recommendations'],
    aiCapabilities: ['200-year pattern matching', 'Multi-agent synthesis', 'Scenario projection'],
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getDocumentsByCategory(category: DocumentCategory): DocumentTemplate[] {
  return EXTENDED_DOCUMENT_TEMPLATES.filter(doc => doc.category === category);
}

export function getDocumentById(id: ExtendedDocumentType): DocumentTemplate | undefined {
  return EXTENDED_DOCUMENT_TEMPLATES.find(doc => doc.id === id);
}

export function getAllCategories(): DocumentCategory[] {
  return [...new Set(EXTENDED_DOCUMENT_TEMPLATES.map(doc => doc.category))];
}

export function getDocumentCount(): number {
  return EXTENDED_DOCUMENT_TEMPLATES.length;
}

// Category metadata for UI - Extended to include all 14 global categories
export const CATEGORY_METADATA: Record<DocumentCategory, { label: string; description: string; icon: string; phase?: string }> = {
  // ===== THE 14 GLOBAL CATEGORIES =====
  'foundation-legal': { label: '1. Foundation & Legal', description: 'LOI, NDA, Term Sheets, MOU - Establishing the legal foundation for deals', icon: 'FileText', phase: 'deal' },
  'strategic-intelligence': { label: '2. Strategic Intelligence', description: 'Business Cases, Feasibility Studies, White Papers - The "what" and "why"', icon: 'Brain', phase: 'entry' },
  'financial-investment': { label: '3. Financial & Investment', description: 'PPM, Financial Models, Valuation - The Accountant Persona', icon: 'DollarSign', phase: 'deal' },
  'risk-due-diligence': { label: '4. Risk & Due Diligence', description: 'DD Reports, AML/KYC, Sanctions - The Skeptic Persona', icon: 'AlertTriangle', phase: 'safety' },
  'government-policy': { label: '5. Government & Policy', description: 'Policy Briefs, Cabinet Memos, PPP Frameworks', icon: 'Building2', phase: 'entry' },
  'partnership-consortium': { label: '6. Partnership & Consortium', description: 'JV Agreements, Consortium Charters - Step 4', icon: 'Handshake', phase: 'deal' },
  'execution-project-management': { label: '7. Execution & PM', description: 'Roadmaps, 100-Day Plans, Gantt Charts - The Operator', icon: 'ClipboardList', phase: 'execution' },
  'governance-board': { label: '8. Governance & Board', description: 'Board Charters, Steering Reports - Step 9', icon: 'Users', phase: 'safety' },
  'human-capital': { label: '9. Human Capital', description: 'Org Charts, Talent Gap Analysis - Step 7', icon: 'Users2', phase: 'execution' },
  'procurement-supply-chain': { label: '10. Procurement & Supply', description: 'RFP, Tender Docs, Vendor Scorecards - The Operator', icon: 'Package', phase: 'execution' },
  'esg-social-impact': { label: '11. ESG & Social Impact', description: 'Environmental, Social License, Community Plans', icon: 'Leaf', phase: 'safety' },
  'regulatory-compliance': { label: '12. Regulatory & Compliance', description: 'Permits, Clearance Timelines - The Regulator', icon: 'Shield', phase: 'safety' },
  'communications-ir': { label: '13. Communications & IR', description: 'Investor Updates, Press Releases, Consultation Decks', icon: 'MessageCircle', phase: 'entry' },
  'asset-infrastructure': { label: '14. Asset & Infrastructure', description: 'Site Selection, Technical Specs - Step 3', icon: 'Building', phase: 'execution' },
  
  // ===== LEGACY CATEGORIES (for backward compatibility) =====
  foundation: { label: 'Foundation', description: 'Initial outreach and preliminary agreements', icon: 'FileText' },
  strategic: { label: 'Strategic', description: 'Strategy, planning, and vision documents', icon: 'Target' },
  legal: { label: 'Legal & Compliance', description: 'Contracts, agreements, and regulatory documents', icon: 'Scale' },
  financial: { label: 'Financial & Investment', description: 'Financial models, valuations, and investment documents', icon: 'DollarSign' },
  risk: { label: 'Risk & Due Diligence', description: 'Risk assessment and due diligence reports', icon: 'AlertCircle' },
  government: { label: 'Government & Policy', description: 'Policy briefs, regulatory filings, and government documents', icon: 'Building2' },
  trade: { label: 'Trade & Commerce', description: 'Trade finance, customs, and supply chain documents', icon: 'Globe' },
  partnership: { label: 'Partnerships', description: 'Partner assessment, alliance frameworks, and collaboration documents', icon: 'Handshake' },
  intelligence: { label: 'Market Intelligence', description: 'Market analysis, competitive intelligence, and research', icon: 'Search' },
  operational: { label: 'Operational', description: 'Implementation plans, project management, and operations', icon: 'Settings' },
  communications: { label: 'Communications', description: 'Press releases, presentations, and stakeholder communications', icon: 'MessageCircle' },
  technical: { label: 'Technical', description: 'Technical specifications and sector-specific documents', icon: 'Cpu' },
  esg: { label: 'ESG & Sustainability', description: 'Environmental, social, and governance reports', icon: 'Leaf' },
  research: { label: 'Research & Academic', description: 'Research papers, analysis, and academic documents', icon: 'BookOpen' },
};

// ============================================================================
// DOCUMENT TYPE COUNT SUMMARY
// ============================================================================

/**
 * TOTAL DOCUMENT TYPES: 200+
 * 
 * Category Breakdown:
 * - Foundation Documents: 10 types
 * - Strategic Documents: 12 types
 * - Legal & Compliance: 16 types
 * - Financial & Investment: 19 types
 * - Risk & Due Diligence: 21 types
 * - Government & Policy: 21 types
 * - Trade & Commerce: 13 types
 * - Partnership & Alliance: 14 types
 * - Market Intelligence: 22 types
 * - Operational: 18 types
 * - Communications & PR: 17 types
 * - ESG & Sustainability: 19 types
 * - Technical & Sector-Specific: 17 types
 * - Research & Academic: 13 types
 * 
 * Page Length Options: 1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 50, 75, 100 pages
 * 
 * Output Formats: PDF, DOCX, HTML, Markdown, Plain Text
 */

