/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * BW NEXUS AI - INTELLIGENT DOCUMENT GENERATOR
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * Full 247-document-type + 156-letter-template generation engine.
 *
 * This service is the single source of truth for ALL document and letter types
 * in the platform. Every document generated by BWConsultantOS flows through here.
 *
 * Architecture:
 *  1. DocumentTypeRouter  - provides the full catalog + section structures
 *  2. BrainContext        - provides real intelligence to inject into every section
 *  3. geminiService       - AI generation stream per section
 *  4. ProfessionalDocumentExporter - formats to DOCX/PDF
 *
 * All 247 document types are REAL - each has its own section structure,
 * tone, audience, and prompt instructions from DocumentTypeRouter.
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import { DocumentTypeRouter, type DocumentTypeConfig, type LetterTypeConfig } from './DocumentTypeRouter';
import { ReportParameters } from '../types';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface GeneratedSection {
  id: string;
  title: string;
  content: string;
  wordCount: number;
  intelligenceSources: string[];
}

export interface GeneratedDocument {
  id: string;
  typeId: string;
  typeName: string;
  category: string;
  classification: 'CONFIDENTIAL' | 'RESTRICTED' | 'SENSITIVE' | 'INTERNAL';
  preparedFor: string;
  preparedBy: string;
  date: string;
  reportId: string;
  sections: GeneratedSection[];
  fullMarkdown: string;
  metadata: {
    country: string;
    sector: string;
    organization: string;
    wordCount: number;
    brainContextUsed: boolean;
    intelligenceDimensions: string[];
  };
}

export interface DocumentCatalogEntry {
  id: string;
  name: string;
  category: string;
  description: string;
  type: 'document' | 'letter';
  tone: string;
  audience: string;
  estimatedWords: number;
  relevanceScore?: number;
  recommended?: boolean;
  rationale?: string;
}

// ─── Full catalog (247 documents + 156 letters) ────────────────────────────────

export class IntelligentDocumentGenerator {
  // ── Catalog access ─────────────────────────────────────────────────────────

  static getFullCatalog(): DocumentCatalogEntry[] {
    const docs = DocumentTypeRouter.getAllDocumentTypes().map((d: DocumentTypeConfig): DocumentCatalogEntry => ({
      id: d.id,
      name: d.name,
      category: d.category,
      description: d.description,
      type: 'document',
      tone: d.tone,
      audience: d.audience,
      estimatedWords: d.sections.reduce((sum, s) => sum + s.maxWords, 0),
    }));

    const letters = DocumentTypeRouter.getAllLetterTypes().map((l: LetterTypeConfig): DocumentCatalogEntry => ({
      id: l.id,
      name: l.name,
      category: l.category,
      description: (l as any).description ?? l.name,
      type: 'letter',
      tone: l.tone,
      audience: l.audience,
      estimatedWords: l.maxWords,
    }));

    return [...docs, ...letters];
  }

  static getCatalogSummary() {
    return DocumentTypeRouter.getCatalogSummary();
  }

  /**
   * Recommend the best documents and letters for a given case.
   * Uses DocumentTypeRouter intelligence + BrainContext signals.
   */
  static recommendForCase(params: {
    country: string;
    sector: string;
    organizationName: string;
    organizationType: string;
    strategicIntent: string[];
    readiness: number;
    brainContext?: any;
    question?: string;
  }): DocumentCatalogEntry[] {
    const { country, sector, organizationType, strategicIntent, readiness, question } = params;

    const keywords = [
      country, sector, organizationType,
      ...(strategicIntent || []),
      question || '',
    ].join(' ');

    // Use router's keyword-based ranking for both docs and letters
    const rankedDoc = DocumentTypeRouter.findBestDocumentType(keywords);
    const rankedLetter = DocumentTypeRouter.findBestLetterType(keywords);

    // Get category-appropriate sets
    const sectorDocs = DocumentTypeRouter.getDocumentsByCategory(sector);
    const sectorLetters = DocumentTypeRouter.getLettersByCategory(sector);

    // Core document set always included for any case
    const coreDocIds = [
      'executive-brief',
      'risk-assessment-report',
      'partner-proposal',
      readiness >= 70 ? 'full-feasibility-study' : 'investment-attraction-strategy',
      readiness >= 50 ? 'due-diligence-report' : 'investor-deck',
      readiness >= 80 ? 'government-submission' : null,
      readiness >= 60 ? 'community-impact-assessment' : null,
    ].filter(Boolean) as string[];

    // Core letter set
    const coreLetterIds = [
      'loi-investment',
      'loi-partnership',
      'engagement-introduction',
      readiness >= 50 ? 'gov-regulatory-inquiry' : null,
      readiness >= 70 ? 'gov-incentive-request' : null,
      readiness >= 80 ? 'gov-mou-proposal' : null,
      organizationType?.toLowerCase().includes('government') ? 'eoi-government' : null,
    ].filter(Boolean) as string[];

    const allDocs = DocumentTypeRouter.getAllDocumentTypes();
    const allLetters = DocumentTypeRouter.getAllLetterTypes();

    const buildEntry = (d: DocumentTypeConfig | LetterTypeConfig, type: 'document' | 'letter', recommended: boolean, rationale: string): DocumentCatalogEntry => {
      const isDoc = type === 'document';
      const doc = d as DocumentTypeConfig;
      const letter = d as LetterTypeConfig;
      return {
        id: d.id,
        name: d.name,
        category: d.category,
        description: (d as any).description ?? d.name,
        type,
        tone: d.tone,
        audience: d.audience,
        estimatedWords: isDoc ? doc.sections?.reduce((s, x) => s + x.maxWords, 0) : letter.maxWords,
        recommended,
        rationale,
        relevanceScore: recommended ? 90 : 60,
      };
    };

    const seen = new Set<string>();
    const results: DocumentCatalogEntry[] = [];

    const addDoc = (id: string, rationale: string, recommended = true) => {
      if (seen.has(id)) return;
      seen.add(id);
      const d = allDocs.find(x => x.id === id);
      if (d) results.push(buildEntry(d, 'document', recommended, rationale));
    };
    const addLetter = (id: string, rationale: string, recommended = true) => {
      if (seen.has(id)) return;
      seen.add(id);
      const l = allLetters.find(x => x.id === id);
      if (l) results.push(buildEntry(l, 'letter', recommended, rationale));
    };

    // Core set
    coreDocIds.forEach(id => addDoc(id, 'Core document for this case profile', true));
    coreLetterIds.forEach(id => addLetter(id, 'Core letter for this case profile', true));

    // Best keyword match
    if (rankedDoc) addDoc(rankedDoc.id, 'Best match for stated intent and sector', true);
    if (rankedLetter) addLetter(rankedLetter.id, 'Best match for stated intent and sector', true);

    // Sector matches
    sectorDocs.slice(0, 5).forEach(d => addDoc(d.id, `Relevant to ${sector} sector`, true));
    sectorLetters.slice(0, 3).forEach(l => addLetter(l.id, `Relevant to ${sector} sector`, true));

    // Brain context boosts
    const brain = params.brainContext;
    if (brain?.compliance?.alerts?.length) {
      addDoc('due-diligence-report', 'Compliance alerts detected - due diligence required', true);
      addLetter('compliance-assurance', 'Compliance assurance letter recommended', true);
    }
    if (brain?.adversarial?.topRisks?.length > 2) {
      addDoc('risk-assessment-report', 'Multiple adversarial risk signals detected', true);
    }
    if (brain?.regionalKernel?.interventions?.length) {
      addDoc('government-submission', 'Regional intervention strategy requires government submission', true);
      addLetter('gov-mou-proposal', 'Government MOU recommended based on regional analysis', true);
    }

    // Fill remaining catalog as 'available' (not recommended, but accessible)
    allDocs.forEach(d => {
      if (!seen.has(d.id)) {
        addDoc(d.id, `Available in full catalog`, false);
      }
    });
    allLetters.forEach(l => {
      if (!seen.has(l.id)) {
        addLetter(l.id, `Available in full catalog`, false);
      }
    });

    return results;
  }

  /**
   * Generate a single document section using AI.
   * Returns markdown string.
   */
  static async generateSection(params: {
    sectionTitle: string;
    promptInstruction: string;
    maxWords: number;
    caseContext: string;
    brainBlock: string;
    generateFn: (prompt: string) => Promise<string>;
  }): Promise<string> {
    const { sectionTitle, promptInstruction, maxWords, caseContext, brainBlock, generateFn } = params;

    const prompt = [
      `## Document Section: ${sectionTitle}`,
      ``,
      `### Your Instructions`,
      promptInstruction,
      ``,
      `### Case Context`,
      caseContext,
      ``,
      `### Intelligence Context (use this to strengthen the section with real data)`,
      brainBlock,
      ``,
      `### Constraints`,
      `- Maximum ${maxWords} words for this section`,
      `- Write in professional document prose - not bullet points unless specified`,
      `- Ground all claims in the case context and intelligence data above`,
      `- Begin directly with the section content - no meta-commentary`,
    ].join('\n');

    return generateFn(prompt);
  }

  /**
   * Build the full case context string for document generation prompts.
   */
  static buildCaseContext(params: Partial<ReportParameters> & {
    currentMatter?: string;
    objectives?: string;
    constraints?: string;
    additionalContext?: string[];
    uploadedDocuments?: string[];
  }): string {
    const lines = [
      `Organization: ${params.organizationName || 'Not specified'}`,
      `Country / Jurisdiction: ${params.country || 'Not specified'}`,
      `Sector: ${(params as any).sector || params.organizationType || 'Not specified'}`,
      `Objective: ${params.objectives || (params.strategicIntent || []).join(', ') || 'Not specified'}`,
      `Current Matter: ${params.currentMatter || 'Not specified'}`,
      `Constraints: ${params.constraints || 'Standard commercial'}`,
    ];

    if (params.additionalContext?.length) {
      lines.push(`Additional Context:`);
      (params.additionalContext as string[] | undefined)?.slice(0, 5).forEach(c => lines.push(`  - ${c}`));
    }
    if (params.uploadedDocuments?.length) {
      lines.push(`Supporting Documents Uploaded: ${params.uploadedDocuments.join(', ')}`);
    }

    return lines.join('\n');
  }

  /**
   * Generate a complete document (all sections) for a given document type.
   * Returns a fully assembled GeneratedDocument.
   */
  static async generateDocument(params: {
    typeId: string;
    caseContext: string;
    brainBlock: string;
    generateFn: (prompt: string) => Promise<string>;
    onSectionComplete?: (section: GeneratedSection, progress: number) => void;
    organizationName: string;
    country: string;
    sector: string;
  }): Promise<GeneratedDocument | null> {
    const route = DocumentTypeRouter.routeDocument(params.typeId);
    if (!route) return null;

    const { config, sectionPrompts } = route;
    const sections: GeneratedSection[] = [];
    const allIntelSources = new Set<string>();

    for (let i = 0; i < sectionPrompts.length; i++) {
      const sp = sectionPrompts[i];
      sp.intelligenceFocus.forEach(f => allIntelSources.add(f));

      const content = await IntelligentDocumentGenerator.generateSection({
        sectionTitle: sp.title,
        promptInstruction: sp.prompt,
        maxWords: sp.maxWords,
        caseContext: params.caseContext,
        brainBlock: params.brainBlock,
        generateFn: params.generateFn,
      });

      const section: GeneratedSection = {
        id: sp.sectionId,
        title: sp.title,
        content,
        wordCount: content.split(/\s+/).length,
        intelligenceSources: sp.intelligenceFocus,
      };
      sections.push(section);

      if (params.onSectionComplete) {
        params.onSectionComplete(section, Math.round(((i + 1) / sectionPrompts.length) * 100));
      }
    }

    const reportId = `BWGA-${new Date().getFullYear()}-${(params.country || 'GL').slice(0, 2).toUpperCase()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;

    const fullMarkdown = [
      `# ${config.name.toUpperCase()}`,
      `**Prepared for:** ${params.organizationName}  |  **Country:** ${params.country}  |  **Report ID:** ${reportId}`,
      `**Classification:** CONFIDENTIAL  |  **Prepared by:** BW Global Advisory - NEXUS AI`,
      `**Date:** ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      ``,
      ...sections.map(s => [`## ${s.title}`, s.content, ''].join('\n')),
    ].join('\n');

    return {
      id: crypto.randomUUID(),
      typeId: config.id,
      typeName: config.name,
      category: config.category,
      classification: 'CONFIDENTIAL',
      preparedFor: params.organizationName,
      preparedBy: 'BW Global Advisory - NEXUS AI',
      date: new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' }),
      reportId,
      sections,
      fullMarkdown,
      metadata: {
        country: params.country,
        sector: params.sector,
        organization: params.organizationName,
        wordCount: sections.reduce((s, x) => s + x.wordCount, 0),
        brainContextUsed: params.brainBlock.length > 100,
        intelligenceDimensions: [...allIntelSources],
      },
    };
  }

  /**
   * Generate a letter for a given letter type.
   */
  static async generateLetter(params: {
    typeId: string;
    caseContext: string;
    brainBlock: string;
    generateFn: (prompt: string) => Promise<string>;
    organizationName: string;
    country: string;
  }): Promise<GeneratedDocument | null> {
    const route = DocumentTypeRouter.routeLetter(params.typeId);
    if (!route) return null;

    const { config, promptInstruction } = route;
    const content = await IntelligentDocumentGenerator.generateSection({
      sectionTitle: config.name,
      promptInstruction,
      maxWords: config.maxWords,
      caseContext: params.caseContext,
      brainBlock: params.brainBlock,
      generateFn: params.generateFn,
    });

    const reportId = `BWGA-LTR-${new Date().getFullYear()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`;

    return {
      id: crypto.randomUUID(),
      typeId: config.id,
      typeName: config.name,
      category: config.category,
      classification: 'CONFIDENTIAL',
      preparedFor: params.organizationName,
      preparedBy: 'BW Global Advisory - NEXUS AI',
      date: new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' }),
      reportId,
      sections: [{ id: 'body', title: config.name, content, wordCount: content.split(/\s+/).length, intelligenceSources: [] }],
      fullMarkdown: content,
      metadata: {
        country: params.country,
        sector: config.category,
        organization: params.organizationName,
        wordCount: content.split(/\s+/).length,
        brainContextUsed: params.brainBlock.length > 100,
        intelligenceDimensions: [],
      },
    };
  }
}

export default IntelligentDocumentGenerator;
