import React, { useState } from 'react';
import { CheckCircle2, Shield, Lock, Users, ArrowRight } from 'lucide-react';

interface LaunchPageProps {
  onAccept: () => void;
}

const LaunchPage: React.FC<LaunchPageProps> = ({ onAccept }) => {
  const [agreed, setAgreed] = useState(false);

  const features = [
    {
      icon: <Shield className="w-5 h-5" />,
      title: 'Strategic Decision Support',
      description: 'All outputs are advisory.',
      color: 'from-blue-50 to-blue-100'
    },
    {
      icon: <Lock className="w-5 h-5" />,
      title: 'Reasoning Governance',
      description: 'Built-in safety layer screens every output before delivery.',
      color: 'from-emerald-50 to-emerald-100'
    },
    {
      icon: <Users className="w-5 h-5" />,
      title: 'Data Privacy',
      description: 'Strict GDPR and Australian Privacy Act compliance.',
      color: 'from-violet-50 to-violet-100'
    },
    {
      icon: <CheckCircle2 className="w-5 h-5" />,
      title: 'Accountability',
      description: 'Users retain final accountability for decisions.',
      color: 'from-amber-50 to-amber-100'
    }
  ];

  return (
    <div className="min-h-screen w-full bg-gradient-to-br from-stone-50 via-blue-50 to-stone-100 flex flex-col">
      {/* Header */}
      <div className="bg-white border-b border-stone-200 sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-stone-900">BW Nexus AI</h1>
            <p className="text-xs text-stone-500 mt-0.5">Intelligence Operating System</p>
          </div>
          <div className="text-right text-xs text-stone-500">
            <p className="font-semibold text-stone-700">Enterprise Ready</p>
            <p>Powered by Advanced Intelligence Engines</p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col items-center justify-center px-6 py-12 md:py-20">
        <div className="max-w-4xl w-full">
          {/* Hero Section */}
          <div className="text-center mb-16">
            <div className="inline-block mb-6">
              <span className="px-4 py-2 bg-blue-100 text-blue-700 rounded-full text-sm font-semibold">
                Launch the Intelligence OS
              </span>
            </div>
            <h2 className="text-5xl md:text-6xl font-bold text-stone-900 mb-6 leading-tight">
              Enterprise Intelligence,
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-emerald-600">
                Governed & Autonomous
              </span>
            </h2>
            <p className="text-xl text-stone-600 max-w-2xl mx-auto mb-12">
              Access the world's most advanced AI-powered consultant platform with built-in governance, ethical reasoning, and strategic intelligence at your fingertips.
            </p>
          </div>

          {/* Features Grid */}
          <div className="grid md:grid-cols-2 gap-6 mb-16">
            {features.map((feature, idx) => (
              <div
                key={idx}
                className={`bg-gradient-to-br ${feature.color} border border-stone-200 rounded-2xl p-8 hover:shadow-lg transition-shadow`}
              >
                <div className="flex items-start gap-4">
                  <div className="text-stone-700 flex-shrink-0 mt-1">
                    {feature.icon}
                  </div>
                  <div>
                    <h3 className="font-bold text-stone-900 mb-2">{feature.title}</h3>
                    <p className="text-stone-600 text-sm leading-relaxed">{feature.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Terms & Conditions */}
          <div className="bg-white border border-stone-200 rounded-2xl p-8 mb-8 shadow-sm">
            <h3 className="text-lg font-bold text-stone-900 mb-6">Platform Terms & Conditions</h3>
            
            <div className="space-y-6 mb-8">
              <div>
                <h4 className="font-semibold text-stone-800 mb-2 flex items-center gap-2">
                  <Shield className="w-4 h-4" />
                  Advisory Nature
                </h4>
                <p className="text-stone-600 text-sm">
                  All outputs, recommendations, and intelligence generated by this platform are advisory in nature. Users are responsible for independently verifying information and exercising professional judgment in decision-making.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-stone-800 mb-2 flex items-center gap-2">
                  <Lock className="w-4 h-4" />
                  Safety & Governance
                </h4>
                <p className="text-stone-600 text-sm">
                  A built-in reasoning governance layer screens every output before delivery. The system applies ethical constraints and validates recommendations against safety standards before presenting results.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-stone-800 mb-2 flex items-center gap-2">
                  <Users className="w-4 h-4" />
                  Data Privacy
                </h4>
                <p className="text-stone-600 text-sm">
                  This platform strictly complies with GDPR, Australian Privacy Act, and other applicable data protection regulations. Your data is encrypted, securely stored, and never used for training purposes without explicit consent.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-stone-800 mb-2 flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4" />
                  User Accountability
                </h4>
                <p className="text-stone-600 text-sm">
                  Users retain full final accountability for all decisions, strategies, and actions taken based on platform outputs. The platform provides intelligence and recommendations; you make the decisions.
                </p>
              </div>
            </div>

            {/* Agreement Checkbox */}
            <label className="flex items-start gap-3 cursor-pointer">
              <input
                type="checkbox"
                checked={agreed}
                onChange={(e) => setAgreed(e.target.checked)}
                className="w-5 h-5 rounded border-stone-300 text-blue-600 mt-0.5 cursor-pointer"
              />
              <span className="text-sm text-stone-600">
                I have read and agree to the platform terms and conditions. I understand that all outputs are advisory and that I retain accountability for my decisions.
              </span>
            </label>
          </div>

          {/* Call-to-Action Button */}
          <div className="flex flex-col gap-4">
            <button
              onClick={onAccept}
              disabled={!agreed}
              className={`w-full py-4 px-6 rounded-xl font-semibold flex items-center justify-center gap-2 transition-all text-lg ${
                agreed
                  ? 'bg-gradient-to-r from-blue-600 to-emerald-600 text-white hover:shadow-xl hover:shadow-blue-600/30 cursor-pointer'
                  : 'bg-stone-200 text-stone-400 cursor-not-allowed'
              }`}
            >
              Launch the Intelligence OS
              <ArrowRight className="w-5 h-5" />
            </button>
            
            <div className="text-center text-xs text-stone-500">
              <p>Get instant access. Install on your device for offline-ready intelligence.</p>
              <p className="mt-1">Available as Progressive Web App on iOS, Android, Mac, and Windows.</p>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-stone-200 bg-white">
        <div className="max-w-6xl mx-auto px-6 py-6 text-center text-xs text-stone-500">
          <p>© 2026 BW Nexus AI. All rights reserved. | Enterprise Intelligence Platform</p>
        </div>
      </div>
    </div>
  );
};

export default LaunchPage;
